# This notebook is to merge all data sources into one file. 

Run this to have complete_data.csv on your computer. You must have synthetic_reformat.csv, as well as the train and two other external datasets from Kaggle. We will be merging all four together to use in model building and training.

In [1]:
from _Setup import *

In [ ]:
syn_df = pd.read_csv(synth_reformat) # Reformatted synthetic data

train_df = pd.read_json(train_path) #  Original training data

external1 = pd.read_json(external1) # External data 1
external2 = pd.read_json(external2) # External data 2

In [3]:
train_df.head()

,document,full_text,tokens,trailing_whitespace,labels
0,7,Design Thinking for innovation reflexion-Avril...,"[Design, Thinking, for, innovation, reflexion,...","[True, True, True, True, False, False, True, F...","[O, O, O, O, O, O, O, O, O, B-NAME_STUDENT, I-..."
1,10,Diego Estrada\n\nDesign Thinking Assignment\n\...,"[Diego, Estrada, \n\n, Design, Thinking, Assig...","[True, False, False, True, True, False, False,...","[B-NAME_STUDENT, I-NAME_STUDENT, O, O, O, O, O..."
2,16,Reporting process\n\nby Gilberto Gamboa\n\nCha...,"[Reporting, process, \n\n, by, Gilberto, Gambo...","[True, False, False, True, True, False, False,...","[O, O, O, O, B-NAME_STUDENT, I-NAME_STUDENT, O..."
3,20,Design Thinking for Innovation\n\nSindy Samaca...,"[Design, Thinking, for, Innovation, \n\n, Sind...","[True, True, True, False, False, True, False, ...","[O, O, O, O, O, B-NAME_STUDENT, I-NAME_STUDENT..."
4,56,Assignment: Visualization Reflection Submitt...,"[Assignment, :, , Visualization, , Reflecti...","[False, False, False, False, False, False, Fal...","[O, O, O, O, O, O, O, O, O, O, O, O, B-NAME_ST..."

In [4]:
train_df.shape

(6807, 5)

In [9]:
external1.head()

,document,full_text,tokens,labels,trailing_whitespace,NAME_STUDENT,EMAIL,USERNAME,ID_NUM,PHONE_NUM,URL_PERSONAL,STREET_ADDRESS,header,context,flavor
0,dtduupvzgt,"Tiburce Evans, https://www.instagram.com/tibur...","[Tiburce, Evans, ,, https://www.instagram.com/...","[B-NAME_STUDENT, I-NAME_STUDENT, O, B-URL_PERS...","[True, False, True, False, True, True, True, F...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,uejmzisyyh,Rose-Mai Rodriguez | PIN # 3814374\n501 Andrea...,"[Rose, -, Mai, Rodriguez, |, PIN, #, 3814374, ...","[B-NAME_STUDENT, I-NAME_STUDENT, I-NAME_STUDEN...","[False, False, True, True, True, True, True, F...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,jzevfvijlw,"Lina Wingate; 095 Terry Via\nTerrymouth, MT 24...","[Lina, Wingate, ;, 095, Terry, Via, \n, Terrym...","[B-NAME_STUDENT, I-NAME_STUDENT, O, B-STREET_A...","[True, False, True, True, True, False, False, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,jqldfongxi,"Lally Scales | Pin # 74,7,9,0, 658-527-2399; l...","[Lally, Scales, |, Pin, #, 74,7,9,0, ,, 658, -...","[B-NAME_STUDENT, I-NAME_STUDENT, O, O, O, B-ID...","[True, True, True, True, True, False, True, Fa...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,qzgtouvmtu,"Li Warfield-Fontana; 001-528-777-2370x08989, p...","[Li, Warfield, -, Fontana, ;, 001, -, 528, -, ...","[B-NAME_STUDENT, I-NAME_STUDENT, I-NAME_STUDEN...","[True, False, False, False, True, False, False...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
external2.head()

,document,full_text,tokens,trailing_whitespace,labels
0,2cd5fb9799fe06349528c33423a0f595,Storytelling Challenge: Crafting Compelling Na...,"[Storytelling, Challenge, :, Crafting, Compell...","[True, False, True, True, True, True, True, Tr...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
1,3cb7ffeb0ef2f45672e53c38b29d610c,Storytelling Challenge: The Power of Narrative...,"[Storytelling, Challenge, :, The, Power, of, N...","[True, False, True, True, True, True, True, Tr...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
2,c172f453e4643ae9c9bc9d8426128217,Storytelling Challenge: The Power of Narrative...,"[Storytelling, Challenge, :, The, Power, of, N...","[True, False, True, True, True, True, True, Tr...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
3,b9edf42553f58bbffa457381a3799770,Storytelling Challenge: Crafting Compelling Na...,"[Storytelling, Challenge, :, Crafting, Compell...","[True, False, True, True, True, True, True, Fa...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4,232dd2bd7be9d3a3ea93cab6e17fcbfa,Storytelling Challenge: The Power of Narrative...,"[Storytelling, Challenge, :, The, Power, of, N...","[True, False, True, True, True, True, True, Tr...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

In [11]:
syn_df.head()

,ESSAY,tokens,trailing_whitespace,labels
0,The digital age has blurred the lines between ...,"['The', 'digital', 'age', 'has', 'blurred', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
1,The digital age has irrevocably woven itself i...,"['The', 'digital', 'age', 'has', 'irrevocably'...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
2,The question of identity in the digital age is...,"['The', 'question', 'of', 'identity', 'in', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
3,The flickering fluorescent lights of the unive...,"['The', 'flickering', 'fluorescent', 'lights',...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
4,## The Unexpected Detour: Finding Community in...,"['The', 'Unexpected', 'Detour', 'Finding', 'Co...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."

In [12]:
# Assuming you have a pandas DataFrame named df that contains the column 'ESSAY'

syn_df.rename(columns={'ESSAY': 'full_text'}, inplace=True)

In [13]:
syn_df.head()

,full_text,tokens,trailing_whitespace,labels
0,The digital age has blurred the lines between ...,"['The', 'digital', 'age', 'has', 'blurred', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
1,The digital age has irrevocably woven itself i...,"['The', 'digital', 'age', 'has', 'irrevocably'...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
2,The question of identity in the digital age is...,"['The', 'question', 'of', 'identity', 'in', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
3,The flickering fluorescent lights of the unive...,"['The', 'flickering', 'fluorescent', 'lights',...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
4,## The Unexpected Detour: Finding Community in...,"['The', 'Unexpected', 'Detour', 'Finding', 'Co...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."

In [14]:
# I want to row bined the syn_df and train_df. How can I do that?

row_binded_df = pd.concat([syn_df, train_df, external1, external2], axis=0)

In [15]:
row_binded_df.head()

,full_text,tokens,trailing_whitespace,labels,document,NAME_STUDENT,EMAIL,USERNAME,ID_NUM,PHONE_NUM,URL_PERSONAL,STREET_ADDRESS,header,context,flavor
0,The digital age has blurred the lines between ...,"['The', 'digital', 'age', 'has', 'blurred', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,The digital age has irrevocably woven itself i...,"['The', 'digital', 'age', 'has', 'irrevocably'...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,The question of identity in the digital age is...,"['The', 'question', 'of', 'identity', 'in', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,The flickering fluorescent lights of the unive...,"['The', 'flickering', 'fluorescent', 'lights',...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,## The Unexpected Detour: Finding Community in...,"['The', 'Unexpected', 'Detour', 'Finding', 'Co...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
# After modification

row_binded_df = row_binded_df[['full_text', 'tokens', 'trailing_whitespace', 'labels']]

In [17]:
row_binded_df

,full_text,tokens,trailing_whitespace,labels
0,The digital age has blurred the lines between ...,"['The', 'digital', 'age', 'has', 'blurred', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
1,The digital age has irrevocably woven itself i...,"['The', 'digital', 'age', 'has', 'irrevocably'...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
2,The question of identity in the digital age is...,"['The', 'question', 'of', 'identity', 'in', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
3,The flickering fluorescent lights of the unive...,"['The', 'flickering', 'fluorescent', 'lights',...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
4,## The Unexpected Detour: Finding Community in...,"['The', 'Unexpected', 'Detour', 'Finding', 'Co...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
...,...,...,...,...
2687,Mind Mapping Tool for Idea Generation and Prob...,"[Mind, Mapping, Tool, for, Idea, Generation, a...","[True, True, True, True, True, True, True, Tru...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
2688,Mind Mapping Tool for Idea Generation and Prob...,"[Mind, Mapping, Tool, for, Idea, Generation, a...","[True, True, True, True, True, True, True, Tru...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
2689,Mind Mapping Tools for Idea Generation and Pro...,"[Mind, Mapping, Tools, for, Idea, Generation, ...","[True, True, True, True, True, True, True, Tru...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
2690,Mind Mapping Tool for Idea Generation and Prob...,"[Mind, Mapping, Tool, for, Idea, Generation, a...","[True, True, True, True, True, True, True, Tru...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
2691,Mind Mapping Tool for Idea Generation and Prob...,"[Mind, Mapping, Tool, for, Idea, Generation, a...","[True, True, True, True, True, True, True, Tru...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

In [19]:
# output directory 
import os
output_path = complete_data

# CSV

row_binded_df.to_csv(output_path, index=False)