# This notebook will be for pre-processing the datasets.

We will also set aside a validation set for our own testing and monitoring purposes.

In [1]:
from _Setup import *

In [2]:
train = pd.read_csv(complete_data)
train.head(5)

,full_text,tokens,trailing_whitespace,labels
0,The digital age has blurred the lines between ...,"['The', 'digital', 'age', 'has', 'blurred', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
1,The digital age has irrevocably woven itself i...,"['The', 'digital', 'age', 'has', 'irrevocably'...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
2,The question of identity in the digital age is...,"['The', 'question', 'of', 'identity', 'in', 't...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
3,The flickering fluorescent lights of the unive...,"['The', 'flickering', 'fluorescent', 'lights',...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."
4,## The Unexpected Detour: Finding Community in...,"['The', 'Unexpected', 'Detour', 'Finding', 'Co...","False,False,False,False,False,False,False,Fals...","['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', ..."

In [3]:
test = pd.read_json(train_path)
test.head()

,document,full_text,tokens,trailing_whitespace,labels
0,7,Design Thinking for innovation reflexion-Avril...,"[Design, Thinking, for, innovation, reflexion,...","[True, True, True, True, False, False, True, F...","[O, O, O, O, O, O, O, O, O, B-NAME_STUDENT, I-..."
1,10,Diego Estrada\n\nDesign Thinking Assignment\n\...,"[Diego, Estrada, \n\n, Design, Thinking, Assig...","[True, False, False, True, True, False, False,...","[B-NAME_STUDENT, I-NAME_STUDENT, O, O, O, O, O..."
2,16,Reporting process\n\nby Gilberto Gamboa\n\nCha...,"[Reporting, process, \n\n, by, Gilberto, Gambo...","[True, False, False, True, True, False, False,...","[O, O, O, O, B-NAME_STUDENT, I-NAME_STUDENT, O..."
3,20,Design Thinking for Innovation\n\nSindy Samaca...,"[Design, Thinking, for, Innovation, \n\n, Sind...","[True, True, True, False, False, True, False, ...","[O, O, O, O, O, B-NAME_STUDENT, I-NAME_STUDENT..."
4,56,Assignment: Visualization Reflection Submitt...,"[Assignment, :, , Visualization, , Reflecti...","[False, False, False, False, False, False, Fal...","[O, O, O, O, O, O, O, O, O, O, O, O, B-NAME_ST..."

In [12]:
missing_values = train.isnull().sum()
print(missing_values)

full_text              2304
tokens                    0
trailing_whitespace       0
labels                    0
dtype: int64

In [9]:
train_Y = train['labels']
train_X = train.drop(columns=['labels'])

train_x, val_x, train_y, val_y = train_test_split(train_X, train_Y, test_size=0.15, random_state=50)

In [13]:
train_x

,full_text,tokens,trailing_whitespace
3965,Challenge and Selection I work for a semico...,"['Challenge', 'and', 'Selection', ' ', 'I', ...","[True, True, True, False, True, True, True, Tr..."
15585,Design Thinking for Innovation\n\nDesign think...,"['Design', 'Thinking', 'for', 'Innovation', '\...","[True, True, True, False, False, True, True, T..."
11662,NaN,"['\n\n', '------------------', '\n\n', 'Challe...","[False, False, False, False, True, True, True,..."
12164,NaN,"['Patricia', 'Compton', ';', 'Username', ':', ...","[True, False, True, False, True, True, True, F..."
5928,REFLECTION -MIND MAPPING\n\nCHALLENGE\n\nFrom ...,"['REFLECTION', '-MIND', 'MAPPING', '\n\n', 'CH...","[True, True, False, False, False, False, True,..."
...,...,...,...
15649,Learning Launch: Testing Ideas and Improving P...,"['Learning', 'Launch', ':', 'Testing', 'Ideas'...","[True, False, True, True, True, True, True, Fa..."
6253,Example Reflection - Learning Launch\n\nChalle...,"['Example', 'Reflection', '-', 'Learning', 'La...","[True, True, True, True, False, False, False, ..."
10123,"Léonie Bassett, leoniebassett\nleonie_bassett1...","['Léonie', 'Bassett', ',', 'leoniebassett', '\...","[True, False, True, False, False, False, False..."
5600,My reflection – Visualization Challenge an...,"['My', 'reflection', '–', 'Visualization', ' ...","[True, True, True, True, False, True, True, Tr..."
14000,"As a student at the university, I have always ...","['As', 'a', 'student', 'at', 'the', 'universit...","[True, True, True, True, True, False, True, Tr..."